config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  devise_for :users
  root 'pages#home'
  resources :chat_rooms, only: [:new, :create, :show, :index]
  get 'home', to: 'pages#home'
  get 'social', to: 'pages#social_media'
  get 'tax-twitter-accounts', to: 'pages#tax_twitter_accounts'
  get 'tax-calculator', to: 'pages#tax_calculator'
  get 'map', to: 'pages#congressional_voting'
  get '/senate/:state', to: 'pages#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy
end

app/models/fox_news_article.rb
class FoxNewsArticle
  attr_reader :headline, :url, :article_snippet, :site

  def initialize(attributes = {})
    @headline = attributes[:title]
    @url = attributes[:url]
    @article_snippet = attributes[:text]
    @site = attributes[:thread][:site]
  end

  def self.find_tax_articles
    results = FoxNewsService.find_tax_articles

    results.map do |result|
      new(result)
    end
  end

end

app/models/liberal_news_article.rb
class LiberalNewsArticle
  attr_reader :headline, :url, :article_snippet, :source

  def initialize(attributes = {})
    @headline = attributes[:title]
    @url = attributes[:url]
    @article_snippet = attributes[:description]
    @source = attributes[:source][:name]
  end

  def self.find_tax_articles
    results = LiberalNewsService.find_tax_articles

    results.map do |result|
      new(result)
    end
  end

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room
  validates :body, presence: true, length: {minimum: 2, maximum: 1000}

  after_create_commit { MessageBroadcastJob.perform_later(self) }

  def timestamp
    created_at.strftime('%H:%M:%S %d %B %Y')
  end
end

app/models/new_york_times_article.rb
class NewYorkTimesArticle
  attr_reader :headline, :url, :article_snippet

  def initialize(attributes = {})
    @headline = attributes[:headline][:main]
    @url = attributes[:web_url]
    @article_snippet = attributes[:snippet]
  end

  def self.find_tax_articles
    results = NewYorkTimesService.find_tax_articles

    results.map do |result|
      new(result)
    end
  end

end

app/models/senator.rb
class Senator
  attr_reader :name,
              :party,
              :twitter_account,
              :facebook_account,
              :youtube,
              :id

  def initialize(attributes = {})
    @id       = attributes[:id]
    @name       = attributes[:name]
    @party      = attributes[:party]
    @twitter_account = attributes[:twitter_id]
    @facebook_account = attributes[:facebook_account]
    @youtube = attributes[:youtube_id]
  end

  def self.find_senators(state)
    results = PropublicaService.find_senators(state)

    results.map do |result|
      new(result)
    end
  end
end

app/models/townhall_news_article.rb
class TownhallNewsArticle
  attr_reader :headline, :url, :article_snippet, :site

  def initialize(attributes = {})
    @headline = attributes[:title]
    @url = attributes[:url]
    @article_snippet = attributes[:text]
    @site = attributes[:thread][:site]
  end

  def self.find_tax_articles
    results = TownhallNewsService.find_tax_articles

    results.map do |result|
      new(result)
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :chat_rooms, dependent: :destroy
  has_many :messages, dependent: :destroy

  def name
    email.split('@')[0]
  end

end

app/models/wall_street_journal_article.rb
class WallStreetJournalArticle
  attr_reader :headline, :url, :article_snippet, :site

  def initialize(attributes = {})
    @headline = attributes[:title]
    @url = attributes[:url]
    @article_snippet = attributes[:text]
    @site = attributes[:thread][:site]
  end

  def self.find_tax_articles
    results = WallStreetJournalService.find_tax_articles

    results.map do |result|
      new(result)
    end
  end

end

app/models/washington_times_article.rb
class WashingtonTimesArticle
  attr_reader :headline, :url, :article_snippet, :site

  def initialize(attributes = {})
    @headline = attributes[:title]
    @url = attributes[:url]
    @article_snippet = attributes[:text]
    @site = attributes[:thread][:site]
  end

  def self.find_tax_articles
    results = WashingtonTimesService.find_tax_articles

    results.map do |result|
      new(result)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  before_action :authenticate_user!

  def index
    @chat_rooms = ChatRoom.all
  end

  def new
    @chat_room = ChatRoom.new
  end

  def create
    @chat_room = current_user.chat_rooms.build(chat_room_params)
    if @chat_room.save
      flash[:success] = 'Chat room added!'
      redirect_to chat_rooms_path
    else
      render 'new'
    end
  end

  def show
    @chat_room = ChatRoom.includes(:messages).find_by(id: params[:id])
    @message = Message.new
  end

  private

  def chat_room_params
    params.require(:chat_room).permit(:title)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @NYT_articles = NewYorkTimesArticle.find_tax_articles
    @liberal_news_articles = LiberalNewsArticle.find_tax_articles
    @fox_news_articles = FoxNewsArticle.find_tax_articles
    @townhall_news_articles = TownhallNewsArticle.find_tax_articles
    @wsj_news_articles = WallStreetJournalArticle.find_tax_articles
    @washington_times_articles = WashingtonTimesArticle.find_tax_articles
  end

  def social_media
    @tax_reform_tweets = SocialMediaContent.twitter_news
  end

  def tax_twitter_accounts
  end

  def tax_calculator
  end

  def congressional_voting
  end

  def show
    state = params[:state].upcase
    @senators = Senator.find_senators(state)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def copyright_generator
    AssefaViewTool::Renderer.copyright("Yohanan Assefa", "All rights reserved")
  end

  def gravatar_for(user, opts = {})
     opts[:alt] = user.name
     image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}?s=#{opts.delete(:size) { 40 }}",
               opts
   end
end

app/helpers/pages_helper.rb
module PagesHelper
  def twitter_parser(twitter_obj)
    regex = %r{
      \b
      (
        (?: [a-z][\w-]+:
         (?: /{1,3} | [a-z0-9%] ) |
          www\d{0,3}[.] |
          [a-z0-9.\-]+[.][a-z]{2,4}/
        )
        (?:
         [^\s()<>]+ | \(([^\s()<>]+|(\([^\s()<>]+\)))*\)
        )+
        (?:
          \(([^\s()<>]+|(\([^\s()<>]+\)))*\) |
          [^\s`!()\[\]{};:'".,<>?«»“”‘’]
        )
      )
    }ix
    format_twitter_object = twitter_obj.split(" ")[2..-1].join(", ")

    format_twitter_object.gsub(regex) do |url|
      "<a href='#{url}' target='_blank'>#{url}</a>"
    end.html_safe
  end

  def user_name_parser(twitter_obj)
    format_twitter_object = twitter_obj.split(" ")[1]
  end

  def image_parser(twitter_obj)
    format_twitter_object = twitter_obj.split(" ")[0]
  end
end

app/views/chat_rooms/_chat_room.html.erb
<h3><%= link_to "#{chat_room.title}", chat_room_path(chat_room) %></h3>

app/views/chat_rooms/index.html.erb
<div class="container">
  <div class="col-md-3"></div>
    <div class="col-md-6 chat-room-style text-center">

      <h1>Enter an Existing Chat Room</h1>

        <%= render @chat_rooms %>
      <hr>
      <p class="lead"><%= link_to 'Create a New Chat Room', new_chat_room_path, class: 'btn btn-primary btn-outline' %></p>

    </div>
  <div class="col-md-3"></div>
</div>

app/views/chat_rooms/new.html.erb
<div class="container">
  <div class="col-md-3"></div>
    <div class="col-md-6 chat-room-style text-center">
      <h1>Create a New Chat Room</h1>
      <br>

      <%= form_for @chat_room do |f| %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, autofocus: true, class: 'form-control' %>
        </div>

        <%= f.submit "Add", class: 'btn btn-primary btn-lg' %>
      <% end %>
    </div>
  <div class="col-md-3"></div>
</div>

app/views/chat_rooms/show.html.erb
<div class="container">
  <div class="col-md-2"></div>
    <div class="col-md-8">
      <h1>#<%= @chat_room.title %></h1>
      <hr>

      <div id="messages" data-chat-room-id="<%= @chat_room.id %>">
        <%= render @chat_room.messages %>
      </div>


      <%= form_for @message, url: '#' do |f| %>
        <div class="form-group">
          <%= f.label :body, "Message" %>
          <%= f.text_area :body, class: 'form-control' %>
          <small class="text-muted">From 2 to 1000 characters</small>
        </div>

        <%= f.submit "Submit", class: 'btn btn-primary btn-block' %>
      <% end %>
    <div class="col-md-2"></div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaxBill2017</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  </head>

  <body>
    <div class="container">
      <%= render "shared/navbar" %>
      <%= yield %>
      <%= render "shared/footer" %>

    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="card">
  <div class="card-block">
    <div class="row">
      <div class="col-md-1">
        <%= gravatar_for message.user %>
      </div>
      <div class="col-md-11">
        <p class="card-text">
          <span class="text-muted"><%= message.user.name %> at <%= message.timestamp %> says</span><br>
          <%= message.body %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/pages/_twitter_accounts_to_follow.html.erb
<div class="col-md-4">
  <p>
    <%= image_tag("ABAtaxsection.jpeg", size: "60x60", class: "style_image") %>
      <a href="https://twitter.com/ABATaxSection?ref_src=twsrc%5Etfw"
      class="twitter-follow-button" data-size="large"
      data-show-count="false">@ABATaxSection</a>
      <script async src="https://platform.twitter.com/widgets.js"
      charset="utf-8"></script>
  </p>

  <p>
    <%= image_tag("BBNATax.jpg", size: "60x60", class: "style_image") %>
      <a href="https://twitter.com/BBNAtax?ref_src=twsrc%5Etfw"
      class="twitter-follow-button"  data-size="large"
      data-show-count="false">@BBNAtax</a>
      <script async src="https://platform.twitter.com/widgets.js"
      charset="utf-8"></script>
  </p>

  <p>
    <%= image_tag("BloombergTax.jpg", size: "60x60", class: "style_image") %>
      <a href="https://twitter.com/BloombergTax?ref_src=twsrc%5Etfw"
      class="twitter-follow-button" data-size="large"
      data-show-count="false">@BloombergTax</a>
      <script async src="https://platform.twitter.com/widgets.js"
      charset="utf-8"></script>
  </p>

  <p>
    <%= image_tag("DavidMorse.jpg", size: "60x60", class: "style_image") %>
    <a href="https://twitter.com/CentristinIdaho?ref_src=twsrc%5Etfw"
    class="twitter-follow-button" data-size="large"
    data-show-count="false">Follow @CentristinIdaho</a>
    <script async src="https://platform.twitter.com/widgets.js"
    charset="utf-8"></script>
  </p>

  <p>
    <%= image_tag("EYUSTaxPolicy.jpg", size: "60x60", class: "style_image") %>
      <a href="https://twitter.com/EY_USTaxPolicy?ref_src=twsrc%5Etfw"
      class="twitter-follow-button" data-size="large"
      data-show-count="false">@EY_USTaxPolicy</a>
      <script async src="https://platform.twitter.com/widgets.js"
      charset="utf-8"></script>
  </p>

  <p>
    <%=  image_tag("GOPSenateFinance.jpg", size: "60x60", class: "style_image")%>
    <a href="https://twitter.com/GOPSenFinance?ref_src=twsrc%5Etfw"
    class="twitter-follow-button" data-size="large"
    data-show-count="false">Follow @GOPSenFinance</a>
    <script async src="https://platform.twitter.com/widgets.js"
    charset="utf-8"></script>
  </p>

  <p>
    <%= image_tag("IRSnews.jpeg", size: "60x60", class: "style_image") %>
    <a href="https://twitter.com/IRSnews?ref_src=twsrc%5Etfw"
    class="twitter-follow-button" data-size="large"
    data-show-count="false">@IRSnews</a>
    <script async src="https://platform.twitter.com/widgets.js"
    charset="utf-8"></script>
  </p>

  <p>
    <%= image_tag("LauraDavison.jpg", size: "60x60", class: "style_image") %>
    <a href="https://twitter.com/intent/tweet?screen_name=laurapdavison&ref_src=twsrc%5Etfw"
    class="twitter-mention-button" data-size="large"
    data-show-count="false">Tweet to @laurapdavison</a>
    <script async src="https://platform.twitter.com/widgets.js"
    charset="utf-8"></script>
  </p>
</div>

<div class="col-md-4">
  <p>
    <%= image_tag("LawProfTodd.jpg", size: "60x60", class: "style_image") %>
    <a href="https://twitter.com/LawProfTodd?ref_src=twsrc%5Etfw"
    class="twitter-follow-button" data-size="large"
    data-show-count="false">Follow @LawProfTodd</a>
    <script async src="https://platform.twitter.com/widgets.js"
    charset="utf-8"></script>
  </p>

  <p>
    <%= image_tag("LindaEvans.jpeg", size: "60x60", class: "style_image") %>
    <a href="https://twitter.com/lifelovetaxes?ref_src=twsrc%5Etfw"
    class="twitter-follow-button" data-size="large"
    data-show-count="false">Follow @lifelovetaxes</a>
    <script async src="https://platform.twitter.com/widgets.js"
    charset="utf-8"></script>
  </p>

  <p>
    <%= image_tag("NATP.jpg", size: "60x60", class: "style_image") %>
    <a href="https://twitter.com/NATPTAX?ref_src=twsrc%5Etfw"
    class="twitter-follow-button" data-size="large"
    data-show-count="false">Follow @NATPTAX</a>
    <script async src="https://platform.twitter.com/widgets.js"
    charset="utf-8"></script>
  </p>

  <p>
    <%= image_tag("TonyNitti.jpg", size: "60x60", class: "style_image") %>
    <a href="https://twitter.com/nittiaj?ref_src=twsrc%5Etfw"
    class="twitter-follow-button" data-size="large"
    data-show-count="false">@Nittiaj</a>
    <script async src="https://platform.twitter.com/widgets.js"
    charset="utf-8"></script>
  </p>

  <p>
    <%= image_tag("Parker'sTaxLibrary.jpeg", size: "60x60", class: "style_image") %>
    <a href="https://twitter.com/ParkerTax?ref_src=twsrc%5Etfw"
    class="twitter-follow-button" data-size="large"
    data-show-count="false">@ParkerTax</a>
    <script async src="https://platform.twitter.com/widgets.js"
    charset="utf-8"></script>
  </p>

  <p>
    <%= image_tag("PWC.png", size: "60x60", class: "style_image") %>
    <a href="https://twitter.com/PwC_Tax?ref_src=twsrc%5Etfw"
    class="twitter-follow-button" data-size="large"
    data-show-count="false">@PwC_Tax</a>
    <script async src="https://platform.twitter.com/widgets.js"
    charset="utf-8"></script>
  </p>

  <p>
    <%= image_tag("RichardRubinDC.jpg", size: "60x60", class: "style_image") %>
    <a href="https://twitter.com/RichardRubinDC?ref_src=twsrc%5Etfw"
    class="twitter-follow-button"   data-size="large"
    data-show-count="false">@RichardRubinDC</a>
    <script async src="https://platform.twitter.com/widgets.js"
    charset="utf-8"></script>
  </p>

  <p>
    <%= image_tag("SenateFinance.jpeg", size: "60x60", class: "style_image") %>
    <a href="https://twitter.com/SenateFinance?ref_src=twsrc%5Etfw"
    class="twitter-follow-button" data-size="large"
    data-show-count="false">@SenateFinance</a>
    <script async src="https://platform.twitter.com/widgets.js"
    charset="utf-8"></script>
  </p>
</div>

<div class="col-md-4">
  <p>
    <%= image_tag("StevenRoll.jpg", size: "60x60", class: "style_image") %>
    <a href="https://twitter.com/Roll_FederalTax?ref_src=twsrc%5Etfw"
    class="twitter-follow-button" data-size="large"
    data-show-count="false">Follow @Roll_FederalTax</a>
    <script async src="https://platform.twitter.com/widgets.js"
    charset="utf-8"></script>
  </p>

  <p>
    <%= image_tag("TaxAlerts.png", size: "60x60", class: "style_image") %>
    <a href="https://twitter.com/Tax_Alerts?ref_src=twsrc%5Etfw"
    class="twitter-follow-button" data-size="large"
    data-show-count="false">Follow @Tax_Alerts</a>
    <script async src="https://platform.twitter.com/widgets.js"
    charset="utf-8"></script>
  </p>

  <p>
    <%= image_tag("TaxAnalysts.png", size: "60x60", class: "style_image") %>
    <a href="https://twitter.com/TaxAnalysts?ref_src=twsrc%5Etfw"
    class="twitter-follow-button" data-size="large"
    data-show-count="false">@TaxAnalysts</a>
    <script async src="https://platform.twitter.com/widgets.js"
    charset="utf-8"></script>
  </p>

  <p>
    <%= image_tag("TaxFoundation.jpg", size: "60x60", class: "style_image") %>
    <a href="https://twitter.com/taxfoundation?ref_src=twsrc%5Etfw"
    class="twitter-follow-button" data-size="large"
    data-show-count="false">@TaxFoundation</a>
    <script async src="https://platform.twitter.com/widgets.js"
    charset="utf-8"></script>
  </p>

  <p>
    <%= image_tag("TaxGirl.png", size: "60x60", class: "style_image") %>
    <a href="https://twitter.com/taxgirl?ref_src=twsrc%5Etfw"
    class="twitter-follow-button" data-size="large"
    data-show-count="false">@TaxGirl</a>
    <script async src="https://platform.twitter.com/widgets.js"
    charset="utf-8"></script>
  </p>

  <p>
    <%= image_tag("TaxPolicyCenter.jpg", size: "60x60", class: "style_image") %>
    <a href="https://twitter.com/TaxPolicyCenter?ref_src=twsrc%5Etfw"
    class="twitter-follow-button"  data-size="large"
    data-show-count="false">@TaxPolicyCenter</a>
    <script async src="https://platform.twitter.com/widgets.js"
    charset="utf-8"></script>
  </p>

  <p>
    <%= image_tag("TaxReformer.jpg", size: "60x60", class: "style_image") %>
    <a href="https://twitter.com/taxreformer?ref_src=twsrc%5Etfw"
    class="twitter-follow-button" data-size="large"
    data-show-count="false">@TaxReformer</a>
    <script async src="https://platform.twitter.com/widgets.js"
    charset="utf-8"></script>
  </p>

  <p>
    <%= image_tag("Tracy.jpeg", size: "60x60", class: "style_image") %>
    <a href="https://twitter.com/TaxAddict?ref_src=twsrc%5Etfw"
    class="twitter-follow-button" data-size="large"
    data-show-count="false">Follow @TaxAddict</a>
    <script async src="https://platform.twitter.com/widgets.js"
    charset="utf-8"></script>
  </p>
</div>

app/views/pages/congressional_voting.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10">
      <h4 align="center">Click on a State to See How Your Senator Voted</h4>
      <div class="map-style" id="map" style="width: 900px; height: 500px;"></div>
      <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV["new_google_api"] %>&callback=initMap"></script>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container">
  <h1 align="center" class="home-page"> Tax Cuts and Jobs Act News Coverage</h1>

  <div class="col-md-4">
    <div class="card card-outline-primary mb-3 text-center">
      <h3>Liberal News</h3>
      <div class="news-scrollbar" id="style-1">
        <div class="force-overflow">
          <div class="card-block">
            <% @liberal_news_articles.each do |article| %>
            <% cache article do %>
            <% if article.source == "CNBC" || article.source == "Al Jazeera English" || article.source == "Reuters" || article.source =="Axios" %>
            <blockquote class="card-blockquote news-card">
              <h4><%= link_to article.headline, article.url %></h4>
              <p><%= article.article_snippet %></p>
              <p><small><%= article.source%></small></p>
            </blockquote>
            <% end %>
            <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="col-md-4">
    <div class="card card-outline-primary mb-3 text-center">
      <h3>New York Times</h3>
      <div class="news-scrollbar" id="style-1">
        <div class="force-overflow">
          <div class="card-block">
            <% @NYT_articles.each do |article| %>
              <% cache article do %>
              <blockquote class="card-blockquote news-card">
                <h4 class="article-headline"><%= link_to article.headline, article.url %></h4>
                <p class="article-snippet"><%= article.article_snippet %></p>
              </blockquote>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>


  <div class="col-md-4">
    <div class="card card-outline-primary mb-3 text-center">
      <h3>Conservative News</h3>
      <div class="news-scrollbar" id="style-1">
        <div class="force-overflow">
      <div class="card-block">

        <% @wsj_news_articles.each do |wsj| %>
        <% cache wsj do %>
          <blockquote class="card-blockquote news-card">
            <h4><%= link_to wsj.headline, wsj.url %></h4>
            <p><%= truncate(wsj.article_snippet, length: 200) %></p>
            <p><small><%= wsj.site %></small></p>
          </blockquote>
        <% end %>
        <% end %>

        <% @fox_news_articles.each do |fox| %>
          <% cache fox do %>
          <blockquote class="card-blockquote news-card">
            <h4><%= link_to fox.headline, fox.url %></h4>
            <p><%= truncate(fox.article_snippet, length: 200) %></p>
            <p><small><%= fox.site %></small></p>
          </blockquote>
          <% end %>
        <% end %>

        <% @townhall_news_articles.each do |townhall| %>
          <% cache townhall do %>
          <blockquote class="card-blockquote news-card">
            <h4><%= link_to townhall.headline, townhall.url %></h4>
            <p><%= truncate(townhall.article_snippet, length: 100) %></p>
            <p><small><%= townhall.site %></small></p>
          </blockquote>
          <% end %>
        <% end %>


        <% @washington_times_articles.each do |washington_time| %>
          <% cache washington_time do %>
          <blockquote class="card-blockquote news-card">
            <h4><%= link_to washington_time.headline, washington_time.url %></h4>
            <p><%= truncate(washington_time.article_snippet, length: 200) %></p>
            <p><small><%= washington_time.site %></small></p>
          </blockquote>
          <% end %>
        <% end %>

        </div>
      </div>
      </div>
    </div>
  </div>

</div>

app/views/pages/show.html.erb
<div class="container">
  <h3 align="center">This is How Your Senators Voted on the 2017 Tax Act</h3>
  <div align="center" class="row">
    <% @senators.each do |senator| %>
    <div class="col-md-6">
      <div class="card senate-card">
        <h4>Senator <%= senator.name %></h4>
        <p>Party Affiliation: <em><%= senator.party %></em></p>
        <p>Twitter Account: <%= link_to "https://twitter.com/#{senator.twitter_account}" %></p>
        <p>Facebook: <%= link_to "https://www.facebook.com/#{senator.facebook_account}" %></p>
        <p>YouTube Page <%= link_to "https://www.youtube.com/user/#{senator.facebook_account}" %></p>
        <% if senator.party == "R" && senator.name != "Bob Corker" %>
          <%= image_tag("yes.jpg", size: "100x100", :style => "border: 1px solid gray") %>
        <% elsif senator.name == "Doug Jones"%>
          <%= image_tag("n_a.jpg", size: "100x100", :style => "border: 1px solid gray") %>
        <% else %>
          <%= image_tag("no.png", size: "100x100", :style => "border: 1px solid gray") %>
        <% end %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/pages/tax_twitter_accounts.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2"></div>
    <h3 align="center">Follow These Twitter Accounts to Stay on Top of Tax Related News</h3>
      <div class="twitter-follow-buttons">
        <%= render "twitter_accounts_to_follow" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="container-fluid">
	<div class="row">
    <nav class="navbar navbar-default navbar-fixed-bottom app-footer" role="navigation">
		<div class="col-md-12">
      <p><%= copyright_generator %></p>
		</div>
  </nav>
	</div>
</div>

app/views/shared/_navbar.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<nav class="navbar navbar-default navbar-inverse" role="navigation">
				<div class="navbar-header">

					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
						 <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
					</button> <a class="navbar-brand" href="/">Tax Cuts and Jobs Act</a>
				</div>

				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav">
						<li>
							<%= link_to "Home", home_path %>
						</li>
						<li>
							<%= link_to "Social Media", social_path %>
						</li>
						<li>
							<%= link_to "Follow on Twitter", tax_twitter_accounts_path %>
						</li>
						<li>
							<%= link_to "Tax Calculator", tax_calculator_path %>
						</li>
						<li>
							<%= link_to "Congressional Voting Record", map_path %>
						</li>
						<% if user_signed_in? %>
							<li><%= link_to "Chat", chat_rooms_path %></li>
							<li class="nav-item dropdown">
				        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
				          Profile <span class="caret"></span></a>
				        <ul class="dropdown-menu">
					 				<li><%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %></li>
									<li role="separator" class="divider"></li>
						 			 <li><%= link_to "Logout", destroy_user_session_path, class: 'nav-link', method: :delete %></li>
				        </ul>
				      </li>
							<% else %>
							<li>
								<%= link_to "Sign Up/Log In", new_user_session_path %>
							</li>
						<% end %>
					</ul>
				</div>
			</nav>
		</div>
	</div>
</div>